# Generated by Django 5.2.1 on 2025-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.CharField(max_length=50, verbose_name='Номер читателя или ФИО')),
                ('need_book', models.CharField(verbose_name='Полное название книги')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
            ],
        ),
    ]
