# Generated by Django 5.2.1 on 2025-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.CharField(max_length=50, verbose_name='Номер читателя или ФИО')),
                ('operation', models.CharField(choices=[('take', 'Взять'), ('return', 'Сдать')], default='take', max_length=10, verbose_name='Операция')),
                ('book_list', models.TextField(verbose_name='Штрихкоды книг')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
            ],
        ),
    ]
