# Generated by Django 5.2.1 on 2025-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'изменение книговыдачи', 'verbose_name_plural': 'изменения книговыдачи'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='operation',
            field=models.CharField(choices=[('Выдать', 'Выдать'), ('Принять', 'Принять')], default='Выдать', max_length=10, verbose_name='Операция'),
        ),
    ]
